# Generated by Django 2.2.12 on 2023-07-05 04:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('start_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.FileField(upload_to='')),
                ('firstname', models.TextField(max_length=60)),
                ('lastname', models.TextField(max_length=60)),
                ('age', models.IntegerField()),
                ('gender', models.TextField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.BigIntegerField()),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('user_type', models.CharField(choices=[('caretaker', 'Caretaker'), ('careseeker', 'Careseeker')], default='None', max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Careseeker',
            fields=[
                ('careuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('state', models.TextField(max_length=60)),
                ('city', models.TextField(max_length=60)),
                ('address', models.TextField(max_length=80)),
                ('order', models.TextField(max_length=100)),
                ('is_careseeker', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('myapp.careuser',),
        ),
        migrations.CreateModel(
            name='Caretaker',
            fields=[
                ('careuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('experience', models.IntegerField()),
                ('id_card_number', models.BigIntegerField()),
                ('profession', models.TextField()),
                ('objective', models.TextField(max_length=300)),
                ('is_caretaker', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('myapp.careuser',),
        ),
    ]
